model:
    seq_length: 60
    input_dim: 168
    num_joints: 24

    n_layers: 8
    n_head: 8
    d_k: 64
    d_v: 64
    d_model: 256
    d_inner: 512
    n_past: 15
    n_future: 15
    n_trans: 30

data:
    data_dir: '../../data/amass_30fps_train_AccadCMU.pt'
    vald_dir: '../../data/amass_30fps_vald_BMLmovi.pt'
    data_set: 'BABEL'
    mask: 'static'

    num_workers: 1
    offset: 20
train:
    batch_size: 6
    lr: 0.0001
    dropout: 0.1
    seed: 1234

    save_per_epochs: 10

    loss_root_weight: 1.0
    loss_fk_weight: 0.01
    loss_ik_weight: 0.01
    loss_quat_weight: 10
    loss_position_weight: 0.1

    num_epoch: 1000
    weight_decay: 0.75

    debug: False
    cuda: True
    method: 'birnn'
    log_dir: 'logs/train_BABEL_rm_birnn'
    output_dir: 'checkpoints/train_BABEL_rm_birnn'

    picture_name: 'train_loss'

test:
    model_dir: 'checkpoints/train_BABEL_rm_birnn/BestAmong_1000.pt'
